spring:
  application:
    name: DRUGMED-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5433/drug
    username: asdf
    password: asdf
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true

  output:
    ansi:
      enabled: always
