spring:
  application:
    name: DRUGMED-SERVICE

  datasource:
    url:  ${DATABASE_URL:jdbc:postgresql://localhost:5433/drug}
    username: ${DATABASE_USERNAME:asdf}
    password: ${DATABASE_PASSWORD:asdf}
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true

  output:
    ansi:
      enabled: always
